// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppwjdakvhpbyyqyrlcgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwd2pkYWt2aHBieXlxeXJsY2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDY3NjAsImV4cCI6MjA2OTgyMjc2MH0.kmeZsWd6qOVYAvmRsR1T4M3WtrZAjzTEaHuKxVcEtSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});